---
title: "Cronograma"
lang: pt-BR
---

Nesta página, você encontrará o cronograma completo da disciplina, com
links para os materiais de cada aula, incluindo slides, dados, 
referências para leitura, entre outros.


::: {.callout-tip icon="false"}
## Como navegar pelos slides

Os slides desta disciplina são interativos e foram produzidos no formato 
**revealjs**.  

Ao abrir um arquivo de slides, utilize:

- **Setas do teclado (← →)** para avançar e voltar  
- Tecla **`F`** para entrar no modo de tela cheia  
- Tecla **`O`** para visualizar todos os slides em formato de grade  
- Tecla **`Esc`** para sair do modo de visão geral  
- Em dispositivos móveis, utilize o gesto de deslizar para os lados  

Os slides são disponibilizados em **HTML autocontido** e abrem em nova aba do seu 
navegador padrão.  
:::




# Aula 1 (05/03/26)

- **Slides:**

  - [Slides Aula 1](slides/01-aula-slides.html){target="_blank"}

- **Leitura/estudo Importantes**

  - [Good enough practices in scientific computing](https://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1005510&type=printable){target="_blank"} 
  
  - [Fostering Better Coding Practices for Data Scientists](https://hdsr.mitpress.mit.edu/pub/8wsiqh1c/release/4){target="_blank"}
  
  - [The History of Data Economy I, II, III, IV - pdf](/artigos/history_of_data_economy.pdf){target="_blank"} 
  
  - [How to Pick a Programming Language - Nature 640, 1116-1117 (2025)](/artigos/d41586-025-01241-6.pdf){target="_blank"}  





# Aula 2 (12/03/26)

- **Slides:**

  - [Slides Aula 2](slides/02-aula-slides.html){target="_blank"}


- **Materiais:**

  - **Arquivo de dados:** [dados_vendas.csv](dados/dados_vendas.csv)

  ::: {.callout-tip}
  ## Como baixar e salvar o arquivo de dados (Windows)

  1. Clique com o botão direito do mouse no link **dados_vendas.csv** acima e selecione 
  **Salvar arquivo como...**.
  2. Verifique se o arquivo que será salvo é **dados_vendas.csv**
  2. Escolha a pasta **Downloads** e clique em **Salvar**.
  3. Abra a pasta do seu projeto no Windows Explorer e localize a pasta 
  `data/raw`.
  4. Copie o arquivo `dados_vendas.csv` da pasta **Downloads** para a pasta 
  **raw**.

  **Dica:** se souber como fazer, no passo 2 você pode salvar o arquivo 
  diretamente na pasta `data/raw`.
  :::
 
 
 
- **Leitura/estudo MUITO importantes**

  - [Cap. 2: Fluxo de trabalho básico](http://pt.r4ds.hadley.nz/workflow-scripts.html){target="_blank"}

  - [Cap. 3: Transformação de dados](http://pt.r4ds.hadley.nz/data-transform.html){target="_blank"}

  - [Cap. 4: Fluxo de trabalho: estilo de código](http://pt.r4ds.hadley.nz/workflow-style.html){target="_blank"}

  - [Cap. 6: Fluxo de trabalho: scripts e projetos](http://pt.r4ds.hadley.nz/workflow-scripts.html){target="_blank"}
  
  - [Good enough practices in scientific computing](https://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1005510&type=printable){target="_blank"} 
  
  - [Fostering Better Coding Practices for Data Scientists](https://hdsr.mitpress.mit.edu/pub/8wsiqh1c/release/4){target="_blank"}





# Aula 3 (19/03/26)

- **Slides:**

  - [Slides Aula 3](slides/03-aula-slides.html){target="_blank"}
  
 
  
- **Lista de Exercícios**

  - [Lista de Exercícios 2](listas-exercicios/02-lista.html){target="_blank"}
  - [Soluções da Lista de Exercícios 2](listas-exercicios/02-lista-solucoes.html){target="_blank"}



- **Materiais:**

  - **Arquivo de dados:** [productionlog_sample.csv](dados/productionlog_sample.csv)


 
- **Leitura/estudo Importantes**

 - [Cap. 3: Transformação de dados](http://pt.r4ds.hadley.nz/data-transform.html){target="_blank"}

 - [Introdução à Linguagem R - Cap. 5](https://pedropark99.github.io/Introducao_R/Capítulos/04-transformacao.html){target="_blank"}




# Aula 4 (26/03/26)

- **Slides:**

  - [Slides Aula 4](slides/04-aula-slides.html){target="_blank"}


- **Lista de Exercícios**

  - [Lista de Exercícios 3](listas-exercicios/03-lista.html){target="_blank"}
  - [Soluções da Lista de Exercícios 3](listas-exercicios/03-lista-solucoes.html){target="_blank"}


- **Materiais da aula:**

  - **Arquivos de dados da Lista 3**

    - **Exercício 1**
      - [produtos.csv](dados/produtos.csv)
      - [vendas.csv](dados/vendas.csv)
      - [clientes.csv](dados/clientes.csv)

    - **Exercício 2**
      - [governanca.csv](dados/governanca.csv)
      - [risco.csv](dados/risco.csv)
      - [contabeis.csv](dados/contabeis.csv)

    - **Exercício 3**
      - [acoes.csv](dados/acoes.csv)
      - [eventos_corporativos.csv](dados/eventos_corporativos.csv)

  ::: {.callout-tip}
  ## Como baixar e salvar os arquivos de dados da Lista 3 (Windows)

  1. Clique com o botão direito do mouse em cada arquivo `.csv` acima e selecione **Salvar arquivo como...**.
  2. Salve os arquivos na pasta **Downloads**.
  3. Abra a pasta do seu projeto no Windows Explorer e localize a pasta `data/raw`.
  4. Copie os arquivos `.csv` da pasta **Downloads** para a pasta `data/raw`.

  **Dica:** se souber como fazer, você pode salvar os arquivos diretamente na pasta `data/raw`.
  :::


- **Leitura/estudo importantes**

  - [Cap. 5: Organização de Dados](http://pt.r4ds.hadley.nz/data-tidy.html){target="_blank"}

  - [Cap. 19 Joins](http://pt.r4ds.hadley.nz/joins.html){target="_blank"}

  - [Tutorial sobre Git e GitHub](https://washingtonsilva.github.io/tutorials/git/){target="_blank"}

  - [Tutorial sobre Markdown](https://washingtonsilva.github.io/tutorials/markdown/){target="_blank"}




# Aula 5 (09/04/26)

- **Slides:**

  - [Slides Aula 5](slides/05-aula-slides.html){target="_blank"}


- **Lista de Exercícios**

  - [Lista de Exercícios 4](listas-exercicios/04-lista.html){target="_blank"}
  - [Soluções da Lista de Exercícios 4](listas-exercicios/04-lista-solucoes.html){target="_blank"}

  
- **Materiais:**

  - **Arquivo de dados:** [demonstracoes.csv](dados/demonstracoes.csv)

  
- **Leitura/estudo importantes**

  - [R para Ciência de Dados - Cap. 25: Funções](http://pt.r4ds.hadley.nz/functions.html){target="_blank"}
  
  - [R para Ciência de Dados - Cap. 26: Iteração](http://pt.r4ds.hadley.nz/iteration.html){target="_blank"}
  
  - [R para Ciência de Dados - Cap. 28: Quarto](http://pt.r4ds.hadley.nz/quarto.html){target="_blank"}
  
  - [Documentação oficial do Quarto: Tutorial](https://quarto.org/docs/get-started/hello/rstudio.html){target="_blank"}





# Aula 6 (16/04/26)

- **Avaliação 1**

  - [Clique aqui para acessar a Avaliação 1](avaliacoes/01-avaliacao.html){target="_blank"}
  
- **Materiais:** Arquivos de dados para a Avaliação 1

  - **Questão 1**
    - [agencias.csv](dados/01-avaliacao/agencias.csv){target="_blank"}
    - [credito_trimestral.csv](dados/01-avaliacao/credito_trimestral.csv){target="_blank"}
    - [inadimplencia.csv](dados/01-avaliacao/inadimplencia.csv){target="_blank"}
  
