---
lang: pt-BR
title: "Programa da Disciplina"
subtitle: "Introdução à Ciência dos Dados 2026/1 <br> Mestrado Profissional em Aministração"
author: "Prof. Dr. Washington S. da Silva"
---


## Objetivo Geral


Trata-se de um curso do tipo *hands-on*. O objetivo primário é equipar 
os mestrandos com conhecimentos fundacionais e ferramentas modernas para 
conduzirem projetos de pesquisa empírica reprodutíveis na área de Finanças, 
desenvolvendo capacidade crítica para implementar modelos empíricos 
robustos, interpretar resultados e comunicar análises computacionais no 
contexto de Finanças e de áreas correlacionadas.

Os fundamentos envolvem computação científica reprodutível, fundamentos 
de teoria da probabilidade e inferência estatística. 

Um foco importante é demonstrar aos mestrandos que as competências e 
habilidades desenvolvidas representam não apenas requisitos para pesquisas 
acadêmicas alinhadas às boas práticas contemporâneas, mas constituem um 
conjunto de ferramentas diferenciadas para o desenvolvimento de soluções 
baseadas em dados para desafios reais do mercado de trabalho atual em 
Finanças e em outras áreas. Para isso, utiliza-se a metodologia CRISP-DM 
como estrutura orientadora para condução de análises de dados.



## Objetivos Especificos

1. Capacitar o mestrando em ferramentas e técnicas modernas de 
computação científica, incluindo: Ambiente de Desenvolvimento 
Integrado RStudio, Sistema de Publicação Quarto, linguagem R, controle 
de versão com Git e GitHub, e boas práticas de organização, documentação 
e compartilhamento de dados e códigos para garantir transparência e 
reprodutibilidade metodológica, tendo como diretriz a metodologia CRISP-DM 
para estruturação do processo analítico.

2. Revisar, de forma aplicada, fundamentos de Probabilidade e 
Estatística necessários para o desenvolvimento, aplicação e 
interpretação crítica de modelos empíricos na área de Finanças, 
incluindo o uso de métodos de simulação para validação de resultados 
e avaliação de incertezas em contextos financeiros.

3. Capacitar o mestrando para a comunicação efetiva de análises e 
resultados através da elaboração de relatórios, visualizações e apresentações 
utilizando o Sistema Quarto e LaTeX, com ênfase na documentação completa 
e transparente do processo de pesquisa que permita a verificação e 
reprodução dos resultados por terceiros.





## Avaliação

O planejamento da disciplina prevê que os pontos referentes às avaliações 
serão distribuídos da seguinte forma:

1. Avaliação 1 = 33 pontos 

2. Avaliação 2 = 33 pontos

3. Avaliação 4 = 34 pontos

Para aprovação, é necessária a obtenção de pelo menos 60 pontos. Como 
em todo planejamento, pode haver alterações conforme o andamento da 
disciplina e o rendimento da turma.





## Bibliografia Básica

WICKHAM, Hadley; ÇETINKAYA-RUNDEL, Mine; GROLEMUND, Garrett. 
**R for Data Science: Import, Tidy, Transform, Visualize, and Model Data**. 
2nd. ed. 2023. O’Reilly Media, Inc. Disponível em: 
[R for Data Science](https://r4ds.hadley.nz){target="_blank"}. 
Tradução em Português disponível em: 
[R para Ciência de Dados](https://cienciadedatos.github.io/pt-r4ds/){target="_blank"}

DEVORE, J. L. **Probabilidade e Estatística para Engenharia e Ciências**. 
São Paulo: Thomson, 2006. Disponível na biblioteca do campus.

SMAY, Chester; KIM, Albert Y. 
**Introduction to Data Science: Data Wrangling and Visualization with R**. 
2nd Edition. CRC Press, 2025. Disponível em: 
[Introduction to Data Science](https://rafalab.dfci.harvard.edu/dsbook-part-1/){target="_blank"}

ISMAY, Chester; KIM, Albert Y.; VALDIVIA, Arturo. **Statistical Inference via Data Science: A ModernDive into R and the Tidyverse**. 2024. 2nd. Ed. CRC Press. 
Disponível em: [ModernDive](https://moderndive.com/v2/){target="_blank"}

CHANG, Winston. **R Graphics Cookbook**. 2025, O'Reilly. Disponível em: 
[R Graphics Cookbook](https://r-graphics.org){target="_blank"}



## Bibliografia Complementar

BLITZSTEIN, Joseph K.; HWANG, Jessica. **Introduction to Probability**. 
2ª ed. CRC Press, 2019. Material de curso disponível em: 
[projects.iq.harvard.edu/stat110](https://projects.iq.harvard.edu/stat110/home){target="_blank"}

TRIOLA, Mário F. **Introdução à Estatística**. 10 edição. Rio de Janeiro: 
LTC, 2008. Disponível na biblioteca do campus.

TIMBERS, TIFFANY; CAMPBELL, Trevor; LEE, Melissa. 
**Data Science: A First Introduction**. 
CRC Press, 2024. Disponível em: [Data Science: A First Introduction](https://datasciencebook.ca){target="_blank"}

ALEXANDER, Rohan. 
**Telling Stories with Data: With Applications in R and Python**. 2023. 
CRC Press. Disponível em: 
[Telling Stories with Data](https://tellingstorieswithdata.com){target="_blank"}

BRYAN, Jennifer. **Happy Git and GitHub for the useR**. 
Disponível em: [happygitwithr.com](https://happygitwithr.com/){target="_blank"}

FARIA, Pedro Duarte. 
**Introdução à Linguagem R: Seus Fundamentos e sua Prática**. 2024. 
Disponível em: 
[Introdução à Linguagem R](https://pedropark99.github.io/Introducao_R/){target="_blank"}





## Recursos Online

- [Manual do Sistema Quarto](https://quarto.org/docs/guide/){target="_blank"}

- [Learn LaTeX in 30 minutes](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes){target="_blank"}

- [Creating a document in Overleaf](https://www.overleaf.com/learn/how-to/Creating_a_document_in_Overleaf){target="_blank"}

- [Harvard Data Science Review](https://hdsr.mitpress.mit.edu/){target="_blank"}





## Ementa

Introdução à Computação Científica Reproduzível: IDE Rstudio, Sistema Quarto, 
Linguagem R e Git/GitHub. Fundamentos de Probabilidade e 
Simulação. Fundamentos de Estatística e Simulação. 





## Conteúdo Planejado

Trata-se apenas de um planejamento e pode ser alterado conforme o andamento 
da disciplina e rendimento da turma.

### 1. Introdução à Computação Científica Reprodutível 

- 1.1. Conceitos Fundamentais de Ciência de Dados
  - 1.1.1. O que é Ciência de Dados?
  - 1.1.2. O ciclo de vida de um projeto de ciência de dados
  - 1.1.3. Ciência de Dados aplicada à Finanças: casos de uso nas linhas 
           de pesquisa do mestrado

- 1.2. Computação Científica Reproduzível
  - 1.2.1. Princípios da pesquisa reproduzível
  - 1.2.2. RStudio e projetos estruturados
  - 1.2.3. Interface e configuração do RStudio
  - 1.2.4. Projetos RStudio: criação, organização e boas práticas
  
- 1.3. Sistema de Publicação Quarto
  - 1.3.1. Fundamentos do Quarto: markdown, código e texto integrados
  - 1.3.2. Formatos de saída para comunicação científica (HTML, PDF, apresentações)
  - 1.3.3. Elementos do Quarto: cabeçalhos, parâmetros, chunks de código
  - 1.3.4. Introdução ao LaTeX para equações e formatação
 
- 1.4. Introdução à Linguagem R
  - 1.4.1. Sintaxe básica, operadores e tipos de dados
  - 1.4.2. Estruturas de dados fundamentais 
  - 1.4.3. Importação e exportação de dados
  - 1.4.4. Manipulação de dados com tidyverse (dplyr, tidyr)
  - 1.4.5. Introdução à criação de funções
  
- 1.5. Controle de Versão com Git e GitHub
  - 1.5.1. Conceitos fundamentais e fluxo de trabalho básico
  - 1.5.2. Criando e mantendo um repositório para o projeto da disciplina
  - 1.5.3. Colaboração e integração com RStudio


### 2. Fundamentos de Probabilidade e Simulação 

- 2.1. Conceitos Básicos de Probabilidade 
  - 2.1.1. Experimentos aleatórios, espaço amostral e eventos
  - 2.1.2. Axiomas da probabilidade
  - 2.1.3. Probabilidade Condicional e Independência
  - 2.1.4. Conceito de variável aleatória
  - 2.1.5. Distribuições discretas de probabilidade 
  - 2.1.6. Distribuições contínuas de probabilidade
  - 2.1.7. Implementação de distribuições de probabilidade em R
  - 2.1.8. Lei dos Grandes Números e Teorema Central do Limite
  - 2.1.9. Características de Distribuições de Probabilidade
    - 2.1.9.1. Valor Esperado, Variância e Desvio-Padrão
    - 2.1.9.2. Assimetria e Curtose
  - 2.1.10. Distribução Conjunta, Marginal e Condicional
    - 2.1.10.1. Covariância e Correlação
  

- 2.2. Simulação de Monte Carlo
  - 2.2.1. Princípios básicos de simulação
  - 2.2.2. Geração de números aleatórios em R
  - 2.2.4. Aplicações em finanças
    - 2.2.4.1. Análise de Viabilidade sob Incerteza
    - 2.2.4.2. Gestão de Risco e Fluxo de Caixa
    - 2.2.4.3. Medidas de Risco: VaR e ES (CVaR) 


### 3. Fundamentos de Inferência Estatística

- 3.1. Análise Exploratória de Dados
  - 3.1.1. Medidas de tendência central/posição e dispersão
  - 3.1.2. Análise exploratória numérica e gráfica

- 3.2. Fundamentos de Inferência Estatística
  - 3.2.1. Amostragem Aleatória 
  - 3.2.2. Estimação pontual e intervalar
  - 3.2.3. Interpretação de intervalos de confiança 
  - 3.2.4. Simulação para compreensão da inferência estatística

- 3.3. Testes de Hipóteses
  - 3.3.1. Conceitos Principais
  - 3.3.2. Testes paramétricos principais
  - 3.3.3. Interpretação de resultados e significância prática vs. estatística
  - 3.3.4. Simulação e Inferência Estatística






## Recursos Didáticos e Materiais de Estudo

Entre os recursos didáticos utilizados na disciplina estão:

- **Materiais Primários para Estudo**:

  - Bibliografia recomendada.
  
  - Slides e notas de aula (disponibilizados no site da disciplina).
  
  - Tutoriais desenvolvidos em Quarto.
  
  - Arquivos quarto (*reports*) demonstrativos (.qmd).

- **Ambiente e Ferramentas**:

  - Repositório GitHub da disciplina para compartilhamento de 
    materiais e submissão de atividades.
    
  - Ambiente virtual de aprendizagem para suporte e comunicação.
  
  - Arquivos de dados reais e simulados para os exemplos.

**Importante**: Os slides, tutoriais e demais recursos disponibilizados 
constituem os materiais primários para estudo e preparação para as 
avaliações, devendo ser utilizados em conjunto com a bibliografia 
recomendada. Todo o material será disponibilizado no site da disciplinar 
e/ou no ambiente virtual de aprendizagem.





## Metodologia de Ensino

A disciplina será conduzida de forma **teórico-aplicada**, com ênfase em
implementação computacional e interpretação substantiva.

- Parte das aulas serão expositivas: apresentação de ferramentas 
computacionais, conceitos e modelos.

- Parte das aulas práticas: **Em cada aula, parte relevante do tempo** 
**será dedicada à elaboração de código R pelos mestrandos**.

- Simulações como ferramenta didática.

- Atividades avaliativas. 




## Plano de Aula

Certamente, o planejamento a seguir está sujeito a alterações, 
conforme o andamento da disciplina e o rendimento da turma.


| Aula | Data      | Tópicos Principais                                 |
|:----:|:---------:|:---------------------------------------------------|
| 1    | 5/3/25    | Apresentação da Disicplina. Introdução à Computação Científica |
| 2    | 12/3/26  | Introdução à Computação Científica                  | 
| 3    | 19/3/26  | Introdução à Computação Científica                  |
| 4    | 26/3/26  | Introdução à Computação Científica                  |
| 5    | 9/4/26   | Introdução à Computação Científica                  |
| 6    | 16/4/26  | Avaliação 1                                         |
| 7    | 23/4/26  | Introdução à Computação Científica                  |
| 8    | 30/4/26  | Probabilidade e Simulação                           |
| 9    | 7/5/26   | Probabilidade e Simulação                           | 
|10    | 14/5/26  | Probabilidade e Simulação                           |
|11    | 21/5/26  | Probabilidade e Simulação                           |
|12    | 28/5/26  | Avaliação 2                                         |
|13    | 11/6/26  | Inferência Estatística                              |
|14    | 18/6/26  | Inferência Estatística                              |
|15    | 25/6/26  | Avaliação 3 / *Encerramento*                        |


